CREATE TABLE puzzledb.channels (
    id INTEGER generated by default as identity PRIMARY KEY,
    channelid BIGINT,
    channeltype VARCHAR(30),
    serverid BIGINT,
    notes VARCHAR(128)
)

SELECT * FROM puzzledb.channels;

CREATE TABLE puzzledb.puzzlehunts (
    id INTEGER generated by default as identity PRIMARY KEY,
    huntid VARCHAR(30),
    puzzlecount INTEGER,
    huntname VARCHAR(128),
    theme VARCHAR(128),
    past BOOLEAN,
    starttime TIMESTAMP,
    endtime TIMESTAMP,
    CONSTRAINT fk_hunt
      FOREIGN KEY(huntid) 
	  REFERENCES puzzledb.puzzlehunts(huntid)
);

SELECT * FROM puzzledb.puzzlehunts;

CREATE TABLE puzzledb.puzzlehunt_puzzles (
    id INTEGER generated by default as identity PRIMARY KEY,
    huntid VARCHAR(30),
    puzzleid VARCHAR(6),
    description VARCHAR(500),
    relatedlink VARCHAR(128),
    points INTEGER,
    requiredpoints INTEGER
);

CREATE TABLE puzzledb.puzzlehunt_solves (
    id INTEGER generated by default as identity PRIMARY KEY,
    huntid VARCHAR(30),
    teamid INTEGER,
    solvetime TIMESTAMP,
    puzzleid VARCHAR(6)
);

CREATE TABLE puzzledb.puzzlehunt_solvers (
    id BIGINT PRIMARY KEY,
    teamid INTEGER,
    huntid VARCHAR(30)
);

CREATE TABLE puzzledb.puzzlehunt_teams (
    id INTEGER generated by default as identity PRIMARY KEY,
    huntid VARCHAR(30),
    teamname VARCHAR(30),
    teamchannel BIGINT
);

CREATE TABLE puzzledb.puzzlehunt_bad_attempts (
    id INTEGER generated by default as identity PRIMARY KEY,
    huntid VARCHAR(30),
    teamid INTEGER,
    solvetime TIMESTAMP,
    puzzleid VARCHAR(6),
    attempt VARCHAR(50)
);

CREATE TABLE puzzledb.puzzlehunt_faqs (
    huntid VARCHAR(30),
    title VARCHAR (200),
    content VARCHAR(2000),
    kind VARCHAR(6)
);



-- To insert --
INSERT INTO puzzledb.puzzlehunts (huntid, puzzlecount, huntname, theme, past) VALUES ('magical-arcade-machine', 0, 'Magical Arcade Machine', 'Retro Video Games', TRUE);
INSERT INTO puzzledb.puzzlehunts (huntid, puzzlecount, huntname, theme, past) VALUES ('avatar', 5, 'Avatar: The Last Puzzlehunt', 'The Last Airbender', FALSE);
INSERT INTO puzzledb.puzzlehunt_puzzles (huntid, puzzleid, name, relatedlink, points, requiredpoints) VALUES ('arcade', 'A1', 'Duck Hunt', 'https://google.com', 10,  0);

-- To update --
UPDATE puzzledb.puzzlehunts SET huntid = 'arcade' where huntid = 'magical-arcade-machine';

-- To alter --
ALTER TABLE exampletablename ADD COLUMN columnname VARCHAR(30);
ALTER TABLE exampletablename DROP COLUMN columnname;
ALTER TABLE exampletablename ALTER COLUMN columnname TYPE VARCHAR(30);