CREATE TABLE puzzledb.channels (
    id INTEGER generated by default as identity PRIMARY KEY,
    channelid BIGINT,
    channeltype VARCHAR(30),
    serverid BIGINT,
    notes VARCHAR(128)
)

SELECT * FROM puzzledb.channels;

CREATE TABLE puzzledb.puzzlehunts (
    id INTEGER generated by default as identity PRIMARY KEY,
    huntid VARCHAR(30),
    puzzlecount INTEGER,
    huntname VARCHAR(128),
    theme VARCHAR(128),
    past BOOLEAN,
    starttime TIMESTAMP,
    endtime TIMESTAMP
);

SELECT * FROM puzzledb.puzzlehunts;

CREATE TABLE puzzledb.puzzlehunt_questions (
    id INTEGER generated by default as identity PRIMARY KEY,
    huntid VARCHAR(30) FOREIGN KEY,
    puzzleid VARCHAR(3),
    description VARCHAR(500),
    relatedlink VARCHAR(128)
);


-- To insert --
INSERT INTO puzzledb.puzzlehunts (huntid, puzzlecount, huntname, theme, past) VALUES ('magical-arcade-machine', 0, 'Magical Arcade Machine', 'Retro Video Games', TRUE);
INSERT INTO puzzledb.puzzlehunts (huntid, puzzlecount, huntname, theme, past) VALUES ('avatar', 5, 'Avatar: The Last Puzzlehunt', 'The Last Airbender', FALSE);

-- To update --
UPDATE puzzledb.puzzlehunts SET huntid = 'arcade' where huntid = 'magical-arcade-machine';

-- To alter --
ALTER TABLE exampletablename ADD COLUMN columnname VARCHAR(30);
ALTER TABLE exampletablename DROP COLUMN columnname;
ALTER TABLE exampletablename ALTER COLUMN columnname TYPE VARCHAR(30);